site_name: reac Documentation
theme: "material"
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: "#087da1"
    accent: "#00a889"
  font:
    text: "Source Sans Pro"

repo_name: 'architecture/reac'
repo_url: 'https://gitlab.infosisglobal.com/architecture/reac'
copyright: 'Copyright © 2021 <a href="https://infosisglobal.com">infosisglobal</a>'

google_analytics:
  - ""
  - "auto"
