export { default as icon1 } from "./icon-1.svg"
export { default as icon2 } from "./icon-2.svg"
export { default as icon3 } from "./icon-3.svg"
export { default as icon4 } from "./icon-4.svg"
export { default as icon5 } from "./icon-5.svg"
export { default as icon6 } from "./icon-6.svg"
